# cluster.yaml
# A cluster with two managed nodegroups
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: talant-managed-cluster
  region: ${AWS_REGION}

managedNodeGroups:
  - name: managed-nodegroup
    minSize: 2
    maxSize: 4
    desiredCapacity: 3
    volumeSize: 20
    # iam:
    #   withAddonPolicies:
    #     externalDNS: true
    #     certManager: true