apiVersion: eksctl.io/v1alpha5
availabilityZones:
- us-east-1a
- us-east-1f
kind: ClusterConfig
managedNodeGroups:
- amiFamily: AmazonLinux2
  desiredCapacity: 3
  instanceType: m5.large
  maxSize: 4
  minSize: 3
  name: talant-node-group
metadata:
  name: talant-cluster
  region: us-east-1